-- ==============================================================================
-- LAGUNA ATHLETIC 2026 · Supabase Setup Seguro (ÚNICA VERSIÓN OFICIAL)
-- ==============================================================================
--
-- ✅ Este es el único script que debes ejecutar en Supabase > SQL Editor.
-- ❌ NO uses el archivo supabase_schema.sql (marcado como obsoleto).
--
-- INSTRUCCIONES:
--   1. Crea un proyecto nuevo en https://supabase.com (o usa uno existente).
--   2. Ve a: Project > SQL Editor > New Query.
--   3. Pega TODO este archivo y haz clic en "Run".
--   4. Ve a: Authentication > Users > Add User y crea el primer usuario admin.
--   5. Copia el UUID del usuario creado y ejecuta la última sentencia
--      UPDATE que aparece al final de este archivo.
--
-- MIGRACIÓN DESDE EL ESQUEMA VIEJO:
--   Si ya ejecutaste supabase_schema.sql anteriormente, este script:
--   - No borra tus tablas ni datos existentes (usa CREATE TABLE IF NOT EXISTS).
--   - Elimina las políticas inseguras antiguas (DROP POLICY IF EXISTS).
--   - Aplica las nuevas políticas seguras por rol.
--
-- ==============================================================================

begin;

-- ============================================================================
-- 1. TIPOS PERSONALIZADOS
-- ============================================================================

do $$
begin
  create type public.app_role as enum ('admin', 'director', 'coach', 'player', 'guardian');
exception when duplicate_object then null;
end $$;

-- ============================================================================
-- 2. TABLAS
-- ============================================================================

-- 2.1 JUGADORES
create table if not exists public.players (
  id               bigint generated by default as identity primary key,
  number           integer not null unique,
  name             text not null,
  position         text not null,
  position_alt     text,
  player_group     text not null default 'Sin Cat.',
  status           text not null default 'Ausente',
  checkin_time     text not null default '-',
  attendance_pct   numeric(5,2) not null default 0 check (attendance_pct between 0 and 100),
  streak           text not null default '0 A',
  starter          boolean not null default false,
  injured          boolean not null default false,
  goals            integer not null default 0 check (goals >= 0),
  assists          integer not null default 0 check (assists >= 0),
  mins             integer not null default 0 check (mins >= 0),
  cards            integer not null default 0 check (cards >= 0),
  reg_status       text not null default 'Activo',
  birthdate        date,
  tutor_name       text,
  phone            text,
  photo            text not null default 'LAGUNA.jpg',
  contacts         jsonb not null default '[]'::jsonb,
  doc_acta         boolean not null default false,
  doc_curp         boolean not null default false,
  doc_medico       boolean not null default false,
  doc_ine          boolean not null default false,
  doc_escolar      boolean not null default false,
  game_info        jsonb not null default '[]'::jsonb,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- 2.2 PERFILES DE USUARIO (vincula auth.users con roles y jugadores)
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  role        public.app_role not null default 'player',
  player_id   bigint unique references public.players(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 2.3 RELACIÓN TUTOR ↔ JUGADOR (un tutor puede tener varios jugadores/hijos)
create table if not exists public.guardian_players (
  guardian_id  uuid not null references public.profiles(id) on delete cascade,
  player_id    bigint not null references public.players(id) on delete cascade,
  created_at   timestamptz not null default now(),
  primary key (guardian_id, player_id)
);

-- 2.4 PAGOS Y FINANZAS
create table if not exists public.payments (
  id              bigint generated by default as identity primary key,
  folio           text not null unique,
  player_id       bigint references public.players(id) on delete set null,
  player_name     text not null,
  tutor_name      text,
  concept         text not null,
  base_amount     numeric(10,2) not null default 0 check (base_amount >= 0),
  discount_pct    numeric(5,2) not null default 0 check (discount_pct between 0 and 100),
  discount_amount numeric(10,2) not null default 0 check (discount_amount >= 0),
  final_amount    numeric(10,2) not null default 0 check (final_amount >= 0),
  method          text not null,
  date            date not null,
  status          text not null default 'Pendiente',
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- 2.5 CALENDARIO Y PARTIDOS
create table if not exists public.calendar_events (
  id           bigint generated by default as identity primary key,
  type         text not null check (type in ('partido', 'entrenamiento', 'evento')),
  title        text not null,
  date         date not null,
  time         text not null,
  location     text not null,
  result       text,
  match_stats  jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- 2.6 ENFERMERÍA Y BAJAS MÉDICAS
create table if not exists public.injuries (
  id               bigint generated by default as identity primary key,
  player_id        bigint not null references public.players(id) on delete cascade,
  player           text not null,
  diagnosis        text not null,
  start_date       date not null,
  estimated_return date,
  status           text not null default 'En Tratamiento',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- 2.7 REGISTRO HISTÓRICO DE ASISTENCIA
create table if not exists public.attendance_logs (
  id           bigint generated by default as identity primary key,
  date         date not null,
  player_id    bigint not null references public.players(id) on delete cascade,
  player_name  text not null,
  status       text not null check (status in ('Presente', 'Ausente', 'Justificado')),
  checkin_time text,
  created_at   timestamptz not null default now(),
  unique (date, player_id)
);

-- 2.8 JUSTIFICACIONES DE AUSENCIAS
create table if not exists public.justifications (
  id           bigint generated by default as identity primary key,
  player_id    bigint not null references public.players(id) on delete cascade,
  detail       text,
  absence_date date not null,
  reason       text not null,
  status       text not null default 'Pendiente' check (status in ('Pendiente', 'Aprobada', 'Rechazada')),
  reviewed_by  uuid references auth.users(id) on delete set null,
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Columna extra por si ya existía la tabla sin la columna detail
alter table public.justifications
  add column if not exists detail text;

-- ============================================================================
-- 3. ÍNDICES DE RENDIMIENTO
-- ============================================================================

create index if not exists payments_player_id_idx           on public.payments (player_id);
create index if not exists calendar_events_date_idx         on public.calendar_events (date);
create index if not exists injuries_player_id_idx           on public.injuries (player_id);
create index if not exists attendance_logs_player_date_idx  on public.attendance_logs (player_id, date desc);
create index if not exists justifications_player_id_idx     on public.justifications (player_id);

-- ============================================================================
-- 4. FUNCIONES Y TRIGGERS DE AUTOMATIZACIÓN
-- ============================================================================

-- 4.1 Auto-actualiza updated_at en cada UPDATE
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 4.2 Crea perfil automáticamente cuando un usuario se registra en Auth
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

-- 4.3 Función auxiliar: ¿es el usuario actual staff (admin/director/coach)?
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role in ('admin', 'director', 'coach')
  );
$$;

-- 4.4 Función auxiliar: ¿tiene el usuario relación con el jugador indicado?
--     (como jugador mismo o como tutor/guardian)
create or replace function public.is_related_to_player(target_player_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    left join public.guardian_players gp on gp.guardian_id = p.id
    where p.id = (select auth.uid())
      and (p.player_id = target_player_id or gp.player_id = target_player_id)
  );
$$;

-- Registrar triggers de updated_at en todas las tablas relevantes
drop trigger if exists set_players_updated_at       on public.players;
create trigger set_players_updated_at       before update on public.players
  for each row execute function public.set_updated_at();

drop trigger if exists set_profiles_updated_at      on public.profiles;
create trigger set_profiles_updated_at      before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_payments_updated_at      on public.payments;
create trigger set_payments_updated_at      before update on public.payments
  for each row execute function public.set_updated_at();

drop trigger if exists set_calendar_events_updated_at on public.calendar_events;
create trigger set_calendar_events_updated_at before update on public.calendar_events
  for each row execute function public.set_updated_at();

drop trigger if exists set_injuries_updated_at      on public.injuries;
create trigger set_injuries_updated_at      before update on public.injuries
  for each row execute function public.set_updated_at();

drop trigger if exists set_justifications_updated_at on public.justifications;
create trigger set_justifications_updated_at before update on public.justifications
  for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- 5. PRIVILEGIOS BASE
-- ============================================================================

-- Revocar acceso anónimo (nadie sin sesión puede leer ni escribir nada)
revoke all on all tables    in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on function public.is_staff()                       from public;
revoke all on function public.is_related_to_player(bigint)     from public;

-- Conceder permisos solo a usuarios autenticados
grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.players,
  public.profiles,
  public.guardian_players,
  public.payments,
  public.calendar_events,
  public.injuries,
  public.attendance_logs,
  public.justifications
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_staff()                    to authenticated;
grant execute on function public.is_related_to_player(bigint)  to authenticated;

-- ============================================================================
-- 6. ROW LEVEL SECURITY (RLS)
-- ============================================================================

alter table public.players           enable row level security;
alter table public.profiles          enable row level security;
alter table public.guardian_players  enable row level security;
alter table public.payments          enable row level security;
alter table public.calendar_events   enable row level security;
alter table public.injuries          enable row level security;
alter table public.attendance_logs   enable row level security;
alter table public.justifications    enable row level security;

-- ── ELIMINAR POLÍTICAS INSEGURAS DEL ESQUEMA VIEJO (supabase_schema.sql) ────
-- Estas políticas abrían acceso total sin autenticación y deben eliminarse.
drop policy if exists "Permitir todo en players"         on public.players;
drop policy if exists "Permitir todo en payments"        on public.payments;
drop policy if exists "Permitir todo en calendar_events" on public.calendar_events;
drop policy if exists "Permitir todo en injuries"        on public.injuries;
drop policy if exists "Permitir todo en attendance_logs" on public.attendance_logs;

-- ── NUEVAS POLÍTICAS SEGURAS ─────────────────────────────────────────────────

-- PLAYERS: Staff lo gestiona todo; jugador/tutor solo ve su registro
drop policy if exists "Staff manage players"         on public.players;
drop policy if exists "Users view their player record" on public.players;
create policy "Staff manage players"
  on public.players for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));
create policy "Users view their player record"
  on public.players for select to authenticated
  using ((select public.is_related_to_player(id)));

-- PROFILES: Cada usuario ve el suyo; Staff los gestiona todos
drop policy if exists "Users read own profile"  on public.profiles;
drop policy if exists "Staff manage profiles"   on public.profiles;
create policy "Users read own profile"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_staff()));
create policy "Staff manage profiles"
  on public.profiles for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));

-- GUARDIAN_PLAYERS: Tutor ve sus enlaces; Staff los gestiona
drop policy if exists "Guardians read their player links" on public.guardian_players;
drop policy if exists "Staff manage guardian links"       on public.guardian_players;
create policy "Guardians read their player links"
  on public.guardian_players for select to authenticated
  using (guardian_id = (select auth.uid()) or (select public.is_staff()));
create policy "Staff manage guardian links"
  on public.guardian_players for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));

-- PAYMENTS: Staff lo gestiona; familias solo ven sus propios pagos
drop policy if exists "Staff manage payments"    on public.payments;
drop policy if exists "Families view their payments" on public.payments;
create policy "Staff manage payments"
  on public.payments for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));
create policy "Families view their payments"
  on public.payments for select to authenticated
  using ((select public.is_related_to_player(player_id)));

-- CALENDAR EVENTS: Todos los autenticados ven el calendario; solo Staff edita
drop policy if exists "Authenticated users view calendar" on public.calendar_events;
drop policy if exists "Staff manage calendar"             on public.calendar_events;
create policy "Authenticated users view calendar"
  on public.calendar_events for select to authenticated using (true);
create policy "Staff manage calendar"
  on public.calendar_events for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));

-- INJURIES: Staff lo gestiona; familias solo ven las de su jugador
drop policy if exists "Staff manage injuries"    on public.injuries;
drop policy if exists "Families view own injuries" on public.injuries;
create policy "Staff manage injuries"
  on public.injuries for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));
create policy "Families view own injuries"
  on public.injuries for select to authenticated
  using ((select public.is_related_to_player(player_id)));

-- ATTENDANCE_LOGS: Staff lo gestiona; familias solo ven la asistencia de su jugador
drop policy if exists "Staff manage attendance"       on public.attendance_logs;
drop policy if exists "Families view own attendance"  on public.attendance_logs;
create policy "Staff manage attendance"
  on public.attendance_logs for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));
create policy "Families view own attendance"
  on public.attendance_logs for select to authenticated
  using ((select public.is_related_to_player(player_id)));

-- JUSTIFICATIONS: Staff gestiona; familias ven y crean las suyas
drop policy if exists "Staff manage justifications"       on public.justifications;
drop policy if exists "Families view own justifications"  on public.justifications;
drop policy if exists "Families create own justifications" on public.justifications;
create policy "Staff manage justifications"
  on public.justifications for all to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));
create policy "Families view own justifications"
  on public.justifications for select to authenticated
  using ((select public.is_related_to_player(player_id)));
create policy "Families create own justifications"
  on public.justifications for insert to authenticated
  with check ((select public.is_related_to_player(player_id)));

-- ============================================================================
-- 7. REALTIME (CAMBIOS EN VIVO MULTI-DISPOSITIVO)
-- Añade cada tabla de forma segura sin borrar la publicación existente.
-- ============================================================================

do $$ begin alter publication supabase_realtime add table public.players;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.payments;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.calendar_events;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.injuries;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.attendance_logs;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.justifications;
exception when duplicate_object then null; end $$;

commit;

-- ============================================================================
-- 8. POST-INSTALACIÓN: ASIGNAR ROL DE ADMINISTRADOR
-- ============================================================================
--
-- Después de crear tu primer usuario en Authentication > Users, ejecuta esta
-- sentencia reemplazando el UUID con el del usuario creado:
--
--   UPDATE public.profiles
--   SET role = 'admin'
--   WHERE id = 'PEGA-AQUI-EL-UUID-DEL-USUARIO-ADMIN';
--
-- Para asignar roles a otros usuarios:
--   'admin'    → Acceso total al sistema
--   'director' → Igual que admin (alias para Directiva)
--   'coach'    → Director Técnico / Auxiliar (lectura/escritura deportiva)
--   'player'   → Jugador (solo ve su propio perfil, asistencia y calendario)
--   'guardian' → Padre/Tutor (ve datos del jugador vinculado en guardian_players)
--
-- Para vincular un tutor a su jugador:
--   INSERT INTO public.guardian_players (guardian_id, player_id)
--   VALUES ('UUID-DEL-TUTOR', ID-NUMERICO-DEL-JUGADOR);
--
-- ============================================================================
