-- LAGUNA ATHLETIC · Supabase setup seguro
-- Ejecuta este archivo UNA vez en Supabase > SQL Editor, en un proyecto nuevo.
-- No ejecutes el antiguo `supabase_schema.sql` después de este archivo.
-- Este esquema exige usuarios autenticados; no expone los datos al rol anon.

begin;

-- 1. Tablas -----------------------------------------------------------------

do $$
begin
  create type public.app_role as enum ('admin', 'director', 'coach', 'player', 'guardian');
exception when duplicate_object then null;
end $$;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  number integer not null unique,
  name text not null,
  position text not null,
  position_alt text,
  player_group text not null default 'Sin Cat.',
  status text not null default 'Ausente',
  checkin_time text not null default '-',
  attendance_pct numeric(5,2) not null default 0 check (attendance_pct between 0 and 100),
  streak text not null default '0 A',
  starter boolean not null default false,
  injured boolean not null default false,
  goals integer not null default 0 check (goals >= 0),
  assists integer not null default 0 check (assists >= 0),
  mins integer not null default 0 check (mins >= 0),
  cards integer not null default 0 check (cards >= 0),
  reg_status text not null default 'Activo',
  birthdate date,
  tutor_name text,
  phone text,
  photo text not null default 'LAGUNA.jpg',
  contacts jsonb not null default '[]'::jsonb,
  doc_acta boolean not null default false,
  doc_curp boolean not null default false,
  doc_medico boolean not null default false,
  doc_ine boolean not null default false,
  doc_escolar boolean not null default false,
  game_info jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'player',
  player_id bigint unique references public.players(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guardian_players (
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (guardian_id, player_id)
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  player_id bigint references public.players(id) on delete set null,
  player_name text not null,
  tutor_name text,
  concept text not null,
  base_amount numeric(10,2) not null default 0 check (base_amount >= 0),
  discount_pct numeric(5,2) not null default 0 check (discount_pct between 0 and 100),
  discount_amount numeric(10,2) not null default 0 check (discount_amount >= 0),
  final_amount numeric(10,2) not null default 0 check (final_amount >= 0),
  method text not null,
  date date not null,
  status text not null default 'Pendiente',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('partido', 'entrenamiento', 'evento')),
  title text not null,
  date date not null,
  time text not null,
  location text not null,
  result text,
  match_stats jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.injuries (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  player text not null,
  diagnosis text not null,
  start_date date not null,
  estimated_return date,
  status text not null default 'En Tratamiento',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  date date not null,
  player_id bigint not null references public.players(id) on delete cascade,
  player_name text not null,
  status text not null check (status in ('Presente', 'Ausente', 'Justificado')),
  checkin_time text,
  created_at timestamptz not null default now(),
  unique (date, player_id)
);

create table if not exists public.justifications (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  detail text,
  absence_date date not null,
  reason text not null,
  status text not null default 'Pendiente' check (status in ('Pendiente', 'Aprobada', 'Rechazada')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.justifications
  add column if not exists detail text;

create index if not exists payments_player_id_idx on public.payments (player_id);
create index if not exists calendar_events_date_idx on public.calendar_events (date);
create index if not exists injuries_player_id_idx on public.injuries (player_id);
create index if not exists attendance_logs_player_date_idx on public.attendance_logs (player_id, date desc);
create index if not exists justifications_player_id_idx on public.justifications (player_id);

-- 2. Automatización ---------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

-- Consultas seguras que las políticas RLS usan internamente.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role in ('admin', 'director', 'coach')
  );
$$;

create or replace function public.is_related_to_player(target_player_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    left join public.guardian_players gp on gp.guardian_id = p.id
    where p.id = (select auth.uid())
      and (p.player_id = target_player_id or gp.player_id = target_player_id)
  );
$$;

drop trigger if exists set_players_updated_at on public.players;
create trigger set_players_updated_at before update on public.players
for each row execute function public.set_updated_at();
drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists set_payments_updated_at on public.payments;
create trigger set_payments_updated_at before update on public.payments
for each row execute function public.set_updated_at();
drop trigger if exists set_calendar_events_updated_at on public.calendar_events;
create trigger set_calendar_events_updated_at before update on public.calendar_events
for each row execute function public.set_updated_at();
drop trigger if exists set_injuries_updated_at on public.injuries;
create trigger set_injuries_updated_at before update on public.injuries
for each row execute function public.set_updated_at();
drop trigger if exists set_justifications_updated_at on public.justifications;
create trigger set_justifications_updated_at before update on public.justifications
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- 3. Privilegios y Row Level Security --------------------------------------

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on function public.is_staff() from public;
revoke all on function public.is_related_to_player(bigint) from public;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.players, public.profiles, public.guardian_players, public.payments,
  public.calendar_events, public.injuries, public.attendance_logs,
  public.justifications to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.is_related_to_player(bigint) to authenticated;

alter table public.players enable row level security;
alter table public.profiles enable row level security;
alter table public.guardian_players enable row level security;
alter table public.payments enable row level security;
alter table public.calendar_events enable row level security;
alter table public.injuries enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.justifications enable row level security;

drop policy if exists "Staff manage players" on public.players;
drop policy if exists "Users view their player record" on public.players;
create policy "Staff manage players" on public.players for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "Users view their player record" on public.players for select to authenticated
  using ((select public.is_related_to_player(id)));

drop policy if exists "Users read own profile" on public.profiles;
drop policy if exists "Staff manage profiles" on public.profiles;
create policy "Users read own profile" on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_staff()));
create policy "Staff manage profiles" on public.profiles for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));

drop policy if exists "Guardians read their player links" on public.guardian_players;
drop policy if exists "Staff manage guardian links" on public.guardian_players;
create policy "Guardians read their player links" on public.guardian_players for select to authenticated
  using (guardian_id = (select auth.uid()) or (select public.is_staff()));
create policy "Staff manage guardian links" on public.guardian_players for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));

drop policy if exists "Staff manage payments" on public.payments;
drop policy if exists "Families view their payments" on public.payments;
create policy "Staff manage payments" on public.payments for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "Families view their payments" on public.payments for select to authenticated
  using ((select public.is_related_to_player(player_id)));

drop policy if exists "Authenticated users view calendar" on public.calendar_events;
drop policy if exists "Staff manage calendar" on public.calendar_events;
create policy "Authenticated users view calendar" on public.calendar_events for select to authenticated using (true);
create policy "Staff manage calendar" on public.calendar_events for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));

drop policy if exists "Staff manage injuries" on public.injuries;
drop policy if exists "Families view own injuries" on public.injuries;
create policy "Staff manage injuries" on public.injuries for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "Families view own injuries" on public.injuries for select to authenticated
  using ((select public.is_related_to_player(player_id)));

drop policy if exists "Staff manage attendance" on public.attendance_logs;
drop policy if exists "Families view own attendance" on public.attendance_logs;
create policy "Staff manage attendance" on public.attendance_logs for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "Families view own attendance" on public.attendance_logs for select to authenticated
  using ((select public.is_related_to_player(player_id)));

drop policy if exists "Staff manage justifications" on public.justifications;
drop policy if exists "Families view own justifications" on public.justifications;
drop policy if exists "Families create own justifications" on public.justifications;
create policy "Staff manage justifications" on public.justifications for all to authenticated
  using ((select public.is_staff())) with check ((select public.is_staff()));
create policy "Families view own justifications" on public.justifications for select to authenticated
  using ((select public.is_related_to_player(player_id)));
create policy "Families create own justifications" on public.justifications for insert to authenticated
  with check ((select public.is_related_to_player(player_id)));

-- 4. Realtime: añade tablas sin borrar la publicación de Supabase -----------

do $$ begin alter publication supabase_realtime add table public.players;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.payments;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.calendar_events;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.injuries;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.attendance_logs;
exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.justifications;
exception when duplicate_object then null; end $$;

commit;

-- DESPUÉS de crear tu primer usuario en Authentication > Users, ejecuta:
-- update public.profiles set role = 'admin' where id = 'PEGA-AQUI-EL-UUID';
